language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
services:
- elasticsearch
- mongodb
install:
- pip install pep8
- pip install pyflakes
- pip install coveralls
- pip install jsonpickle
- pip install pymongo elasticsearch
- pip freeze
- python setup.py install
before_script:
- pep8 . --exclude test,docs,examples,build --ignore=W503,E123
- pyflakes libnessus/*.py
- sleep 10
script: nosetests --with-coverage --cover-package=libnessus
after_script:
- curl -XDELETE localhost:9200/nessus_reports
after_success: coveralls
deploy:
  provider: pypi
  user: Michael.Boutillier
  password:
    secure: HqRFlOIZPM4GwfqetCHRIwFCorYqKN5qhk/Gfk6s17oEUz2xvuKUJ3W+TQMJzyGe57idc0U1ZQfmI2g2lcCEAvYx/CPEo9pFC1XOVfXZWbkvmnNYDUgtcDYnLNTOQ4d8JR14WK/muTjVgU2y8Pyo/+/5t7DqiLopFLikyKcNab8=
  on:
    tags: true
    repo: bmx0r/python-libnessus
